name: ctRPG
version: '${project.version}'
main: com.crystalneko.ctrpg.CtRPG
api-version: '1.20'
commands:
  job:
    usage: /job
    description: 加入职业命令
  jobadmin:
    usage: /jobAdmin
    description: 职业管理命令
    aliases: [joba]
permissions:
  ctrpg.job.command.admin:
    default: false